version: '3.3'

services:
  DiscordOauth:
    build:
      context: ./SyncPortal
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
        - .env

  # DiscordOauth:
  #   build:
  #     context: ./DiscordOauth
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8001:8000"
  #   env_file:
  #       - .env
